### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by zaikin-andrew** [GoodMood-Tech/store-admin-panel#1]
Use the  `/login`  route. When submitting, send a POST request to `http://api.reklambutiken.com/v1/login`  with this data: 
```json
{ "username": "${username}", "password": "${password}" }
```

This will return a  token that you will use to authorize against the api from now on. 
Save this token in localstorage. You can use 
username: `sandbox` password: `sandbox` to test.

- add auth guard which checks user token in LS and use it for each route
- add auth service with login/logout requests and adding/removing token to/from LS

**Comment by user-one-myteam** [comment]
2-3 часа

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: Store Admin Panel - https://app.hubstaff.com/projects/174350
Date Range: 12/21/16 - 12/21/16
Work session total: 1:22:22
Grand total: 1:22:22
