### ISSUE TITLE
Simple table

### ISSUE THREAD

**Issue by zaikin-andrew** [GoodMood-Tech/store-admin-panel#2]
Make a new route: /products that should contain a table like:
```html
<table><tr><th>ID</th><th>Name</th></tr></table>
```
Fetch products from here: GET  `http://api.reklambutiken.com/v1/products`

You need to send this `header` to authorize:
`Authorization: {$token}`

- add new route with auth guard and base page component
- add service in the same folder with this request
- add table with incoming data

**Comment by user-one-myteam** [comment]
2-3 часа

**Comment by user-one-myteam** [comment]
via Hubstaff
User: User One
Project: Store Admin Panel - https://app.hubstaff.com/projects/174350
Date Range: 12/21/16 - 12/21/16
Work session total: 1:01:04
Grand total: 1:01:04
